[package]
name = "ill-backend-repo"
version = "0.1.0"
edition = "2021"

[lints.clippy]
pedantic = "deny"
unwrap_used = "deny"
missing_errors_doc = "allow"
module_name_repetitions = "allow"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
